Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,22 +21,28 @@ jobs:
                     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
                     unzip awscliv2.zip >/dev/null;
                     sudo ./aws/install >/dev/null;
-                    date;
-                    sudo mv aws2 .aws; sudo mv .aws ~;
+                    date; sudo mv aws2 .aws; sudo mv .aws ~;
                     chmod 555 ~/.aws; chmod 444 ~/.aws/*;
-                    aws s3 ls s3://consbucket4;
-                    aws s3 cp file7.html s3://consbucket4 ; 
-                    aws s3 cp . s3://consbucket4 --exclude "*" --include "file*"; 
-                    aws s3 cp . s3://consbucket4 --exclude "*" --include "*.html" ; 
-                    aws s3 cp "index.html" s3://consbucket4 ;  
-                    aws s3 cp "image1.png" s3://consbucket4 ; echo "after s3 copy...";
+                    aws s3 ls s3://consbucket4 >/dev/null;
+                    
                     sudo apt-get update > /dev/null;
                     sudo apt install default-jdk --fix-missing >/dev/null;
                     sudo apt install junit4 > /dev/null;
                     javac HelloWorld.java; java HelloWorld;
                     javac --class-path=/usr/share/java/junit4.jar:. testsofHelloWorld.java;
                     javac --class-path=/usr/share/java/junit4.jar:. TestRunner.java;
-                    java --class-path=/usr/share/java/junit4.jar:. TestRunner; echo $?; echo "EOF";
+                    java --class-path=/usr/share/java/junit4.jar:. TestRunner;
+                    if [ $? -eq 0 ] ; then
+                        aws s3 cp file7.html s3://consbucket4 ; 
+                        aws s3 cp . s3://consbucket4 --exclude "*" --include "file*"; 
+                        aws s3 cp . s3://consbucket4 --exclude "*" --include "*.html" ; 
+                        aws s3 cp "index.html" s3://consbucket4 ;  
+                        aws s3 cp "image1.png" s3://consbucket4 ; 
+                        echo "after s3 copy...";
+                    else
+                        echo "SOME TESTS FAILED";
+                        return 1;
+                    fi
       
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
